# -*- coding: utf-8 -*-
"""image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7VTBxZX21X5F2eq03xpIa-O-Ctx76cU
"""

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
from IPython.display import display

!pip install -q diffusers accelerate

if torch.cuda.is_available():
    device = "cuda"
    dtype = torch.float16
    print("GPU detected! Running on CUDA...")
else:
    device = "cpu"
    dtype = torch.float32
    print("GPU not available.")

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=dtype
)
pipe = pipe.to(device)

user_prompt = input("\nEnter Image Prompt: ")

# 3. Generate & Display Image
print("\nGenerating Image")
image = pipe(user_prompt).images[0]

display(image)
image.save("generated_image.png")
print("\nImage Generated Successfully and saved as generated_image.png!")

